### PR TITLE
Make label for currency setting (Shop->Settings->Localization) more explicit.

### PR DESCRIPTION
**Pull request by prinzdezibel**

### CODE REVIEW

**Comment by aaronjudd** [comment]
@queso Also related to reactioncommerce/reaction#336  reactioncommerce/reaction#389

**Comment by aaronjudd** [comment]
This PR makes total sense to me and probably is needed even with the method refactors.

**Comment by prinzdezibel** [comment]
@aaronjudd Yes, we have a long delay here as well and I was wondering too, if it could be related with #389

**Comment by aaronjudd** [comment]
:+1: thanks.

**Pull request merged**
