### PR TITLE
Tweak the product find to work the way it is intended. Fixes #396

### PR DESCRIPTION
**Pull request by queso**

### CODE REVIEW

**Comment by queso** [comment]
Fixes https://github.com/reactioncommerce/reaction/issues/396

**Comment by aaronjudd** [comment]
Maybe also update the query in `routing.coffee` `setProduct` to use the `$regex` in this PR as well?

**Comment by queso** [comment]
Ok, will take a look.

**Comment by queso** [comment]
@aaronjudd looks like routing.coffee already uses the same regex in setProduct up top: https://github.com/reactioncommerce/reaction-core/blob/development/common/routing.coffee#L5

**Pull request merged**
