### PR TITLE
Regarding multi vendor seller permissions for Products publications, and small fixes

### PR DESCRIPTION
**Pull request by boboci9**
Hi Aaron,
- I added a suggestion for the multi vendor support to check for seller's permission in case the shops parameter is added to the Products publication we would check if the current user is a seller in any of the shops and publish the products, this would still have to be revised because we are still publishing to many products so we could have a brainstorming when you have time on how to publish only the necessary data, but the changes I made could work for now.
- I also added Boolean to the argument check for the product update because it returned error when isVisible parameter was changed.
- In the new version I was getting error for the states dropdown because the formId there in the this object so I added a fix to get the country value.

Best regards,
Bogi

### CODE REVIEW

**Comment by queso** [comment]
@boboci9 or @aaronjudd is there any potential downside to revealing non-visible products to shop admins that aren't admins of other shops?

This solution just checks that you are at least a shop admin for one shop and then it will reveal all products to any shop you asked for, including non-visible products for shops you don't admin.

**Comment by boboci9** [comment]
Yes that was my concern as well that I tried describing in the PR description, the issue is that the shops parameter to the Products publication was added because of multi vendor setups, so when you have a marketplace and multiple shops selling through that one marketplace we need to publish products from multiple shops.
A solution could be to add the condition with an or {either product is in shopId and visible or it's in a shopId where the current user is an admin} ? Or do you have a better idea?

**Comment by aaronjudd** [comment]
I've been thinking that it's probably time to consider more complex publishing / workflow rules. I think maybe "isVisible" could be refactored to a more flexible object:

**Products**

```
	active: "false" || boolean  # replace isVisible for creator
	publish: [ beginDate, endDate] # replaces isVisible for public
```
When a product is `active`, it's visible / not visible to it's creator.

When a product is published we add a start date, with an *optional *end date.

There could potentially be multiple date ranges (for example, to publish only on specific weekends)

When viewing a grid, we'll add some UI element to toggle the appearance / publication in grids of "publish:false" products.

**Shops**


	workflowRoles:[
		products:
			create: [ {shopId,'createProduct'} ]
			publish: [ {shopId,['admin','owner'] } ]
			view:[ {shopId,'guest'} ]
	]

Here's some use cases for this publishing structure:

* A user with appropriate permissions  `['admin','owner','createProduct']` can create a product.
* Shop A should be able to give Shop B access to unpublished view
* Shop A (uber shop) could have permission to publish products from Shop B (and perhaps Shop B cannot their own products)
* Shop B can publish products, but only to their shop (i.e.: not Shop A)
* Shop B users can view products from Shop A, but only when shop A allows viewing
* default permissions can be setup like in example definition, as the fallback in case workflowRoles isn't defined.


Possibly we should consider route/tags in publishing permissions as well, for instance, if a certain user has permissions to publish without review in just one category.

* workflowRoles could be specific to Tag

**Comment by spencern** [comment]
I like this proposal for more complex publishing and visibility rules. 
Here's a few more suggestions for product visibility rules and flags
CatalogVisible: *true*: product is will show up in relevant catalog pages, category searches, etc
CatalogVisible: *false*: product will only be visible via direct link

Another frequent request I've seen for other ecommerce products is for a way to lock down products to certain users types or roles that aren't necessarily administrators. (e.g. wholesale, prodeal, etc). 

Could potentially be accomplished with something like `visibleToRole`: ['wholesaler', 'prodeal-novice', 'prodeal-intermediate`]

**Comment by aaronjudd** [comment]
@spencern good point on the catalogVisible idea - of course, that's what a tag does right? if there was no tag, it could only be found with a direct link.  Otherwise tag to include in category. I wonder if that's enough? Can you see an exception to that?

re: user role lockdown: I'm thinking the proposed format handles this.. 

` view:[ {shopId,'guest'} ]` would be like: `"visibleToRole": "shopId": "role"`

**Comment by spencern** [comment]
@aaronjudd 
I think that just not tagging something could work to exclude it from the catalog, but ideally (in the future perhaps) we will be able to create 'smart' catalogs that organize ever product from a given vendor, within a certain price range, etc. It's in those cases that having an include/exclude flag might be nice.

Re: user role lockdown, you are correct, view should be sufficient for that use case.

**Comment by boboci9** [comment]
Sorry my new changes went to the open pull request, I dodn't know they will be automatically merged, I wanted to create a new pull request with the last 2 commits. Let me know if I should create a new one somehow.
To sum them up:
- I added the defaultRoles to the shops and the user creation as we discussed on gittter
- I change the image upload to take the product shopId and added a parameter for the Media publication because when we have products from multiple shops we will need their photos as well

**Comment by queso** [comment]
I think you have to put those commits on a new branch if you don’t want them to be in this PR.


--Josh Owens | 513-678-7081 | http://joshowens.me | @joshowens

**Comment by aaronjudd** [comment]
It's ok this time - I had to do a manual merge anyways.  I had the fix for states in another commit also but was taking a while to get the branch ready.  But agreed, normally  feature branches are probably easier to manage than directly into development - just makes it easier to keep the PR's clean.

**Pull request merged**
