### PR TITLE
With bower and velocity

### PR DESCRIPTION
**Pull request by aaronjudd**
bower, publishProduct method, tests
- implement bower and replace static lib
- updates to payment templates, lib methods
- add publishProduct method, tests
- adds publishProduct(productId) method
- refactors client ui to use publishProduct
- adds tests for publishProduct
- updated Alert to use a ID for placement grid
- patches some issues when using only core

### CODE REVIEW

**Comment by boboci9** [comment]
Hi, I made pulled the latest version from the development branch but I get the following errors
 Bower:  { [Error: No cached version for git@github.com:sdrdis/jquery.serialize-hash.git#*] stack: [Getter] }
Bower:  { [Error: Failed to execute "git ls-remote --tags --heads git@github.com:openexchangerates/money.js.git", exit code of #128] stack: [Getter] }
=> Errors while upgrading packages:           
                                              
While building package reactioncommerce:core:
<runJavaScript-39>:239:55: Cannot read property 'name' of undefined (compiling
lib/bower.json)
at getDependencies (<runJavaScript-39>:239:55)
at <runJavaScript-39>:251:5
at Function._.each._.forEach (<runJavaScript-37>:147:22)
at getDependencies (<runJavaScript-39>:250:5)
at bowerHandler (<runJavaScript-39>:117:35)
at Package (<runJavaScript-39>:277:10)

error: File not found: lib/bower/jquery.ui/ui/core.js
error: File not found: lib/bower/jquery.ui/ui/widget.js
error: File not found: lib/bower/jquery.ui/ui/mouse.js
error: File not found: lib/bower/jquery.ui/ui/position.js
error: File not found: lib/bower/jquery.ui/ui/autocomplete.js
error: File not found: lib/bower/jquery.ui/ui/sortable.js
error: File not found: lib/bower/jquery.ui/ui/draggable.js
error: File not found: lib/bower/jquery.ui/ui/droppable.js
error: File not found: lib/bower/jquery.ui/ui/effect.js
error: File not found: lib/bower/jquery.ui/ui/effect-slide.js
error: File not found: lib/bower/jquery.ui/ui/menu.js
error: File not found: lib/bower/autosize/dest/autosize.js
error: File not found: lib/bower/collapsible/jquery.collapsible.js
error: File not found: lib/bower/openexchangerates.accounting/accounting.min.js
error: File not found: lib/bower/openexchangerates.money/money.js
error: File not found: lib/bower/jquery.tagsinput/jquery.tagsinput.js
error: File not found: lib/bower/jquery.cookie/jquery.cookie.js

Do you have any ideas what am I doing wrong?

**Comment by aaronjudd** [comment]
you should be seeing: 
```
=> Started MongoDB.
Bower:  { [Error: No cached version for git@github.com:sdrdis/jquery.serialize-hash.git#*] stack: [Getter] }
Bower:  jquery.payment v1.2.3 successfully installed
Bower:  autosize v3.0.0 successfully installed
Bower:  i18next v1.8.0 successfully installed
Bower:  collapsible v1.2.1 successfully installed
Bower:  swiper v3.0.6 successfully installed
Bower:  imagesloaded v3.1.8 successfully installed
Bower:  jquery.cookie v1.4.1 successfully installed
Bower:  jquery.tagsinput v1.3.2 successfully installed........
````

It sort of looks like you had a remote network failure.

try:
stop meteor
rm package/s/reaction-core/lib/bower/*
restart meteor

**Comment by aaronjudd** [comment]
@boboci9 try `mkdir -p package/reaction-core/lib/bower` as well, I'm thinking maybe I need to commit the empty bower directory?

**Comment by boboci9** [comment]
I have created this lib/bower folder but even is I pull everything again it is still empty.

**Pull request merged**
