### PR TITLE
give currentTag a default value

### PR DESCRIPTION
**Pull request by cooloney**
currentTag here might be undefined, then method call will fail. Giving a
empty string as a default value solves this issue.

Signed-off-by: Bryan Wu <cooloney@gmail.com>

### CODE REVIEW

**Comment by mikemurray** [comment]
I think it would be better to fix the check in the server method "products/updateProductTags" to Match.OneOf(String, null, undefined). and defaulting it to a blank string if null / undefined

**Comment by cooloney** [comment]
@mikemurray got you, I will update that soon.

**Comment by cooloney** [comment]
@mikemurray looks like currentTagsId is not used in updateProductTags function. do we still need to give a default value like a blank string?

**Comment by aaronjudd** [comment]
I’m able to repeat this by copying a word from weibo, but it fails to let me add anything (presumably because the input is not recognized), I’m wondering if your keyboard/locale,etc when typing english (or chinese), is some how creating a input that’s not understood. If you use “” you’re bypassing a required field in the product schema. I’ll take a look at it right now - but, but we might need to create an issue to document the steps to replicate this, as the answer might not be easy as it seems.

I do not think we should change the check here, or not in that way, we should actually change the check to use

The Schema is such:
```
ReactionCore.Schemas.Tag = new SimpleSchema({
  name: {
    type: String,
    index: 1
  },
  slug: {
    type: String
  },
  position: {
    type: Number,
    optional: true
  },
  relatedTagIds: {
    type: [String],
    optional: true,
    index: 1
  },
  isTopLevel: {
    type: Boolean
  },
  shopId: {
    type: String,
    index: 1,
    autoValue: ReactionCore.shopIdAutoValue,
    label: "Tag shopId"
  },
  createdAt: {
    type: Date
  },
  updatedAt: {
    type: Date
  }
});

```

**Comment by aaronjudd** [comment]
Closing, this is a duplicate of https://github.com/reactioncommerce/reaction/issues/384 and is most likely related to getSlug not working.

**Pull request closed without merging**
